language: cpp

compiler:
  - clang
  - gcc

before_install:
  - wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
  - sudo apt-get install -qfy build-essential autoconf autotools-dev lttoolbox-dev pkg-config libxml2-dev libutfcpp-dev

script:
  - $CXX --version
  - export V=1 VERBOSE=1
  - autoreconf -fvi
  - ./configure
  - make -j4
  - make test
  - sudo make install
